String decodeKeyValue(long result) {
  switch(result) {
    case 0x16:
      return "0";
    case 0xC:
      return "1"; 
    case 0x18:
      return "2"; 
    case 0x5E:
      return "3"; 
    case 0x8:
      return "4"; 
    case 0x1C:
      return "5"; 
    case 0x5A:
      return "6"; 
    case 0x42:
      return "7"; 
    case 0x52:
      return "8"; 
    case 0x4A:
      return "9"; 
    case 0x9:
      return "EQ"; 
    case 0x15:
      return "VOL+"; 
    case 0x7:
      return "VOL-"; 
    case 0xD:
      return "200+";
    case 0x19:
      return "100+";         
    case 0x44:
      return "PREV";   
    case 0x43:
      return "PLAY/PAUSE";   
    case 0x40:
      return "NEXT";   
    case 0x45:
      return "CH-";   
    case 0x47:
      return "CH+";   
    case 0x46:
      return "CH";       
    case 0x0:
      return "ERR";   
    default :
      return "ERR"; 
  }
}